CREATE TABLE `configFiscais` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nfseAtivo` boolean NOT NULL DEFAULT false,
	`nfseInscricaoMunicipal` varchar(20),
	`nfseUltimoRps` int DEFAULT 0,
	`nfseSerieRps` varchar(10) DEFAULT '1',
	`nfseRegimeTributario` enum('mei','simples_nacional','lucro_presumido','lucro_real'),
	`nfseNaturezaOperacao` varchar(255),
	`nfseUsuarioAcesso` varchar(255),
	`nfseSenhaAcesso` varchar(255),
	`nfseCertificadoValido` boolean DEFAULT false,
	`nfseCertificadoVencimento` timestamp,
	`nfeAtivo` boolean NOT NULL DEFAULT false,
	`nfeInscricaoEstadual` varchar(20),
	`nfeSerie` int DEFAULT 1,
	`nfeUltimoNumero` int DEFAULT 0,
	`nfeExcluirIcmsBaseCalculo` boolean DEFAULT false,
	`nfeEstadoSubstituto` varchar(2),
	`nfeInscricaoEstadualSubstituto` varchar(20),
	`nfceAtivo` boolean NOT NULL DEFAULT false,
	`nfceIdCsc` varchar(10),
	`nfceCodigoCsc` varchar(50),
	`usuarioId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `configFiscais_id` PRIMARY KEY(`id`)
);
